export { SupabaseUserRepository } from "./SupabaseUserRepository"
export { SupabaseAlumniRepository } from "./SupabaseAlumniRepository"
export { SupabaseIntroductionRepository } from "./SupabaseIntroductionRepository"
export { SupabaseQuizQuestionRepository } from "./SupabaseQuizQuestionRepository"
export { SupabaseQuizSessionRepository } from "./SupabaseQuizSessionRepository"
export { SupabaseProfileRepository } from "./SupabaseProfileRepository"
export { SupabaseSubscriptionRepository } from "./SupabaseSubscriptionRepository"
export { SupabaseNewsletterRepository } from "./SupabaseNewsletterRepository"
